services:
  - type: web
    name: saudi-iban-generator
    env: docker
    plan: free
    buildCommand: "composer install --no-dev && php artisan migrate --force"
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:CbpI/k9IdQUWo6uDvjpdFDobrRnsd+MPAVRHOxQCV4s=
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /app/database/database.sqlite
